# TRHub V3 Amlogic A113X quad core 1Gb RAM SoC, eMMC 8G
BOARD_NAME="LinuxBox"
BOARDFAMILY="trhub"
BOOTCONFIG="trhub_linuxbox_defconfig"
KERNEL_TARGET="current,edge"
PACKAGE_LIST_BOARD="libubootenv-tool apparmor rfkill bluetooth bluez bluez-tools dbus-broker libprotobuf-lite32 python3-pip python3-dev python3.11-venv watchdog cifs-utils curl dbus jq libglib2.0-bin lsb-release network-manager nfs-common systemd-journal-remote systemd-resolved udisks2 wget systemd-timesyncd ipset iputils-arping iputils-ping libturbojpeg0 libcjson1"
PACKAGE_LIST_BOARD_REMOVE="chrony resolvconf"
DEFAULT_CONSOLE="serial"
BOOT_LOGO="no"

